<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net35</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>TSforge</AssemblyName>
    <IncludeSourceRevisionInInformationalVersion>False</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibTSforge\LibTSforge.csproj" />
  </ItemGroup>

</Project>
